### ISSUE TITLE
Error running jest

### ISSUE THREAD

**Issue by sablair** [stack-auth/stack#274]
I am in the process of creating jest tests and find that any page that uses the component below:
```tsx
'use client';

import { useStackApp } from '@stackframe/stack';
type Props = {
  caption: string;
};

export default function GoogleLoginButton({ caption }: Props) {
  const app = useStackApp();
  return (
    <button
      onClick={async () => await app.signInWithOAuth('google')}
      className="w-full bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow my-2"
    >
      {caption}
    </button>
  );
}
```
gets this error:
```
Details:

    /Users/batusai/Documents/projects/passion-proj/node_modules/@stackframe/stack-sc/dist/index.default.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export const cookies = undefined;
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      11 |     <button
      12 |       onClick={async () => await app.signInWithOAuth('google')}
    > 13 |       className="w-full bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow my-2"
         |                ^
      14 |     >
      15 |       {caption}
      16 |     </button>

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (node_modules/@stackframe/stack/src/lib/stack-app.ts:1:31)
      at Object.<anonymous> (node_modules/@stackframe/stack/src/providers/stack-provider.tsx:2:88)
      at Object.<anonymous> (node_modules/@stackframe/stack/src/index.tsx:1:42)
      at Object.<anonymous> (src/components/GoogleLoginButton.tsx:13:16)
      at Object.<anonymous> (src/app/page.tsx:12:67)
      at Object.<anonymous> (__tests__/page.test.tsx:8:54)
```

Expected:
- Test is executed and failed

Actual
- Test is never actually carried out (as it fails before it gets to start)

**Comment by sablair** [comment]
My bad. I was creating a unit test, and as such I should have created a mock to eliminate the dependency. All's good now.
